class AgentRepoCreator

  TEMPLATE_OWNER = "swombat"
  TEMPLATE_REPO = "helix-kit-agents"
  API_ROOT = "https://api.github.com"

  Result = Data.define(:owner, :name, :html_url, :ssh_url, :clone_url, :default_branch)
  DeployKey = Data.define(:id, :private_key, :public_key)

  class GitHubError < StandardError; end

  def self.validate_token!(token)
    response = request(:get, "/user", token: token)
    response.fetch("login")
  end

  def initialize(account:, agent:, repo_name:, private_repo: true, template_owner: TEMPLATE_OWNER, template_repo: TEMPLATE_REPO)
    @account = account
    @agent = agent
    @repo_name = repo_name
    @private_repo = private_repo
    @template_owner = template_owner
    @template_repo = template_repo
  end

  def create_repo!
    body = {
      owner: account.github_login,
      name: repo_name,
      private: private_repo,
      include_all_branches: false
    }
    response = github_request(:post, "/repos/#{template_owner}/#{template_repo}/generate", body: body)

    Result.new(
      owner: response.dig("owner", "login") || account.github_login,
      name: response.fetch("name"),
      html_url: response.fetch("html_url"),
      ssh_url: response.fetch("ssh_url"),
      clone_url: response.fetch("clone_url"),
      default_branch: response["default_branch"].presence || "main"
    )
  end

  def create_deploy_key!(repo)
    private_key, public_key = generate_deploy_key
    body = {
      title: "HelixKit #{agent.name} deploy key",
      key: public_key,
      read_only: false
    }
    response = github_request(:post, "/repos/#{repo.owner}/#{repo.name}/keys", body: body)

    DeployKey.new(
      id: response.fetch("id").to_s,
      private_key: private_key,
      public_key: public_key
    )
  end

  def commit_runtime_files!(repo, identity_files:, credentials_yml_enc:, deploy_yml:)
    files = {}
    identity_files.each do |path, content|
      next if path == "memory/.keep"

      files["identity/#{path}"] = content
    end
    files["credentials.yml.enc"] = credentials_yml_enc
    files["deploy.yml"] = deploy_yml

    files.each do |path, content|
      put_file(repo, path, content, message: "Prepare #{agent.name} external runtime")
    end
  end

  def deploy_yml(repo)
    <<~YAML
      # Generated by HelixKit for #{agent.name}.
      # For local testing, bin/deploy --local uses this repo path on your machine.
      agent_id: #{agent.name.to_s.parameterize.presence || "agent-#{agent.id}"}
      endpoint_url: http://localhost:4000
      provider: anthropic
      model: claude-haiku-4-5
      image_tag: #{repo.name}:latest
      shim_port: 4000
      mem_limit: 8g
    YAML
  end

  private

  attr_reader :account, :agent, :repo_name, :private_repo, :template_owner, :template_repo

  def put_file(repo, path, content, message:)
    require "base64"
    require "cgi"

    encoded_path = path.split("/").map { |part| CGI.escape(part) }.join("/")
    body = {
      message: message,
      content: Base64.strict_encode64(content),
      branch: repo.default_branch
    }

    with_repo_retry do
      github_request(:put, "/repos/#{repo.owner}/#{repo.name}/contents/#{encoded_path}", body: body)
    end
  end

  def generate_deploy_key
    require "open3"
    require "tmpdir"

    Dir.mktmpdir("helixkit-agent-key") do |dir|
      key_path = File.join(dir, "deploy_key")
      comment = "helixkit-#{agent.to_param}@#{repo_name}"
      _output, error, status = Open3.capture3(
        "ssh-keygen", "-t", "ed25519", "-N", "", "-C", comment, "-f", key_path
      )
      raise GitHubError, "Could not generate deploy key: #{error.presence || status.inspect}" unless status.success?

      [ File.read(key_path), File.read("#{key_path}.pub") ]
    end
  end

  def with_repo_retry
    attempts = 0
    begin
      attempts += 1
      yield
    rescue GitHubError => e
      raise if attempts >= 5 || !e.message.match?(/404|Not Found/i)

      sleep(1)
      retry
    end
  end

  def github_request(method, path, body: nil)
    self.class.request(method, path, token: account.github_pat, body: body)
  end

  def self.request(method, path, token:, body: nil)
    require "base64"
    require "cgi"
    require "json"
    require "net/http"
    require "uri"

    uri = URI("#{API_ROOT}#{path}")
    request = request_class(method).new(uri)
    request["Accept"] = "application/vnd.github+json"
    request["Authorization"] = "Bearer #{token}"
    request["Content-Type"] = "application/json"
    request["User-Agent"] = "HelixKit"
    request["X-GitHub-Api-Version"] = "2022-11-28"
    request.body = JSON.generate(body) if body

    response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(request) }
    parsed = response.body.present? ? JSON.parse(response.body) : {}

    return parsed if response.code.to_i.between?(200, 299)

    message = parsed["message"].presence || response.message
    raise GitHubError, "GitHub API #{response.code}: #{message}"
  end

  def self.request_class(method)
    {
      get: Net::HTTP::Get,
      post: Net::HTTP::Post,
      put: Net::HTTP::Put
    }.fetch(method)
  end

end
