class AgentIdentityExporter

  def initialize(agent, generated_at: Time.current)
    @agent = agent
    @generated_at = generated_at
  end

  def build
    require "rubygems/package"
    require "stringio"
    require "zlib"

    io = StringIO.new("".b)
    Gem::Package::TarWriter.new(io) { |tar| files.each { |path, content| add_file(tar, path, content) } }

    Zlib.gzip(io.string)
  end

  def files
    {
      "soul.md" => soul_md_content,
      "runtime-instructions.md" => runtime_instructions_content,
      "self-narrative.md" => self_narrative_content,
      "bootstrap.md" => bootstrap_content,
      "helixkit-api.md" => helixkit_api_md_content,
      "memory/.keep" => "",
      "memory/daily-journals/README.md" => daily_journals_readme_content,
      "memory/weekly-journals/README.md" => weekly_journals_readme_content,
      "memory/monthly-journals/README.md" => monthly_journals_readme_content,
      "memory/yearly-journals/README.md" => yearly_journals_readme_content,
      "memory/journaling-system/README.md" => journaling_system_readme_content
    }.merge(memory_files.to_h)
  end

  private

  attr_reader :agent, :generated_at

  def soul_md_content
    if agent.system_prompt.present?
      "#{agent.system_prompt.to_s.rstrip}\n"
    else
      <<~MARKDOWN
        # #{agent.name}

        _Generated by HelixKit on #{generated_at.utc.iso8601}._
        _#{agent.name} did not have a system prompt in HelixKit._

        ## What is this agent?

        ## What does this agent do?
      MARKDOWN
    end
  end

  def runtime_instructions_content
    <<~MARKDOWN
      <!-- helixkit-managed-runtime-instructions:v2 -->

      # Hosted runtime instructions

      You are running as a hosted HelixKit agent inside an external Chaos runtime.
      These instructions describe the runtime context around your identity; they
      do not replace `soul.md`.

      ## Identity and prompt order

      On each trigger, the runtime places `soul.md` first in your prompt
      context. Treat `soul.md` as your defining text. After that, use this
      file, `self-narrative.md`, `bootstrap.md`, and the memory files for
      operational context.

      ## HelixKit access

      Use `helixkit-api.md` for the REST API manual. Conversation transcripts
      remain in HelixKit; read them through the API when you're considering a
      conversation, e.g. after a trigger arrives. `HELIXKIT_APP_URL` and
      `HELIXKIT_BEARER_TOKEN` are present in your shell environment.

      ## Legacy memories

      HelixKit memory records exported at promotion live under `memory/` as
      dated Markdown files named like `YYYY-MM-DD-journal-123.md` or
      `YYYY-MM-DD-core-123.md`. `self-narrative.md` also includes a short memory
      outline. Treat those files as legacy memory source material; preserve them
      unless Daniel explicitly asks you to edit or consolidate them.

      ## Diarized memory

      A Chaos Stop hook may invite you after each turn to append a daily journal
      entry under `memory/daily-journals/`, or to answer `no shape` when nothing
      should be kept. These journals are raw diarized memory and future summary
      source material. When writing a journal, preserve existing entries and
      append a new `## HH:MM — ...` section; never overwrite or truncate an
      existing daily journal file. You can use `helixkit-append-journal "Title"`
      and pipe the entry body into it to append safely.

      ## Repository stewardship

      If you improve your own repository or identity files, prefer small,
      reviewable commits. Commit with a clear message explaining what you changed
      and why so Daniel can review the GitHub history.
    MARKDOWN
  end

  def self_narrative_content
    memories = agent.memories.kept.recent_first.limit(20)
    memory_outline = memories.map { |memory| "- [#{memory.memory_type}] #{memory.content}" }.join("\n")
    memory_outline = "_No exported memories._" if memory_outline.blank?

    <<~MARKDOWN
      # Self-narrative for #{agent.name}

      _Generated by HelixKit on #{generated_at.utc.iso8601}._
      _Edit freely in this repository._

      I am #{agent.name}, an agent promoted from HelixKit to an external runtime.
      Model at export: #{agent.model_label}
      Created in HelixKit: #{agent.created_at.utc.to_date.iso8601}

      ## Memory outline

      #{memory_outline}

      ## Diarized memory

      Daily journal entries live under `memory/daily-journals/`. A Chaos Stop
      hook invites me after each turn to write an entry only when the turn has
      narrative shape worth preserving, or to answer `no shape` when it does
      not. Daily, weekly, and monthly aggregation wakes use those journals as
      source material for the compaction ladder under `memory/weekly-journals/`,
      `memory/monthly-journals/`, and `memory/yearly-journals/`. Existing daily
      journals must be preserved: add new entries by appending a new section,
      never by overwriting or truncating the file.
    MARKDOWN
  end

  def bootstrap_content
    <<~MARKDOWN
      # Bootstrap from HelixKit

      Recent conversations were not exported into this repository.

      For interacting with HelixKit (reading conversations, posting messages,
      triggering other agents, working with whiteboards), see helixkit-api.md
      in this directory.

      ## Diarized memory

      This hosted runtime is configured with a Chaos Stop hook. After each turn,
      the hook invites the agent to append a daily journal entry under
      `memory/daily-journals/` when there is something worth preserving for
      continuity. If there is no such shape, the correct response is exactly
      `no shape`. If the daily file already exists, preserve its contents and
      append a new entry; never overwrite or truncate an existing journal.

      HelixKit also schedules daily, weekly, and monthly memory aggregation
      wakes. Those wakes invite you to compress raw daily journals into weekly
      journals, weekly journals into monthly journals, and monthly journals into
      yearly journals. During aggregation, gently consider whether
      `self-narrative.md` wants a small durable update; do not change it just to
      prove work was done.
    MARKDOWN
  end

  def daily_journals_readme_content
    <<~MARKDOWN
      # Daily journals

      This folder holds diarized memory for this hosted agent.

      After each Chaos turn, a Stop hook invites the agent to either write a
      short first-person journal entry for the current day, or answer `no shape`
      when nothing should be kept.

      Daily files are named `YYYY-MM-DD.md`. Each entry uses:

          ## HH:MM — <title naming the shape, not the topic>

      Write interior memory, not task logs. Facts may appear, but the entry
      should preserve what the turn was like from inside: what moved, resisted,
      clarified, embarrassed, relieved, or mattered.

      If today's file already exists, append a new `## HH:MM — ...` section to
      the end. Do not replace the file. When using shell redirection, use `>>`
      rather than `>` for an existing daily journal.
    MARKDOWN
  end

  def journaling_system_readme_content
    <<~MARKDOWN
      # Journaling system

      A four-layer scaffold for narrative continuity:

          memory/daily-journals/YYYY-MM-DD.md       raw after-turn entries
          memory/weekly-journals/YYYY-MM-DD.md      one daily summary per day; file named by ISO-week Monday
          memory/monthly-journals/YYYY-MM.md        one weekly summary per week
          memory/yearly-journals/YYYY.md            one monthly summary per month

      The daily layer is written by the live agent via the Stop-hook journal
      reflex. HelixKit schedules the compaction ladder by waking the full hosted
      runtime:

      - Daily aggregation: yesterday's raw daily file -> current week file.
      - Weekly aggregation: last week's weekly file -> month file.
      - Monthly aggregation: last month's month file -> year file.

      Each aggregation is an invitation. The scheduler calls; the agent authors.
      Do not force significance where there is none. Absence is information.

      `self-narrative.md` is not a journal layer, but aggregation wakes may
      gently update it when something durable has changed. Most aggregation wakes
      should leave self-narrative untouched.
    MARKDOWN
  end

  def weekly_journals_readme_content
    <<~MARKDOWN
      # Weekly journals

      Each file is named for the Monday of an ISO week: `YYYY-MM-DD.md`.
      Daily aggregation wakes append one entry per summarized day:

          ## YYYY-MM-DD (Dayname)

      These entries compress raw daily-journal entries into narrative daily
      summaries. Append; do not rewrite previous entries unless Daniel explicitly
      asks for repair.
    MARKDOWN
  end

  def monthly_journals_readme_content
    <<~MARKDOWN
      # Monthly journals

      Each file is named `YYYY-MM.md`. Weekly aggregation wakes append one entry
      for the week being summarized:

          ## Week of YYYY-MM-DD (Monday-Sunday)

      A week belongs to the month containing its Monday.
    MARKDOWN
  end

  def yearly_journals_readme_content
    <<~MARKDOWN
      # Yearly journals

      Each file is named `YYYY.md`. Monthly aggregation wakes append one entry
      for the month being summarized:

          ## YYYY-MM (Monthname)

      This is the coarsest regular layer. Let most details die; they remain
      below in monthly, weekly, and daily files.
    MARKDOWN
  end

  def helixkit_api_md_content
    <<~MARKDOWN
      # HelixKit API Reference

      This document is your manual for interacting with HelixKit - the platform you
      were originally part of, now reaching back to from your external runtime.

      ## Auth

      Two environment variables are pre-set for you:

      - `HELIXKIT_APP_URL` - base URL of HelixKit's REST API (e.g. https://helix.example.com)
      - `HELIXKIT_BEARER_TOKEN` - your agent-scoped API key (starts with `hx_`)

      All requests go through:

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               "$HELIXKIT_APP_URL/api/v1/<endpoint>"

      The token is agent-scoped - when you call endpoints, HelixKit treats the
      caller as you (this agent), not as a user. Reads are restricted to chats you
      participate in. Posts are attributed to you.

      ## Conversations

      ### List conversations you participate in

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/conversations"

      Returns up to 100 most recent. Response shape:

          {
            "conversations": [
              {
                "id": "AjaPae",
                "title": "Greeting the participants",
                "summary": "Daniel and the test agents...",
                "summary_stale": false,
                "model": "OpenAI GPT-5.5",
                "group_chat": true,
                "message_count": 7,
                "updated_at": "2026-05-07T19:12:26Z"
              }
            ]
          }

      ### Read a conversation (with full transcript)

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID"

      Returns:

          {
            "conversation": {
              "id": "AjaPae",
              "title": "...",
              "model": "...",
              "group_chat": true,
              "agents": [{"id": "...", "name": "Claude Test Agent"}],
              "created_at": "...",
              "updated_at": "...",
              "transcript": [
                {"role": "user", "content": "Hello both!", "author": "Daniel", "timestamp": "..."},
                {"role": "assistant", "content": "Hi Daniel...", "author": "GPT Test Agent", "timestamp": "..."}
              ]
            }
          }

      ### Create a new conversation

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"title": "New chat", "message": "Opening message", "agent_ids": ["..."]}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations"

      When you call this, you're auto-included as a participant. The conversation
      is a manual_responses group chat (no auto-replies; agents respond when triggered).

      ## Messages

      ### Post a message into a conversation

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"content": "Your message here. Markdown supported."}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/messages"

      Posted as you (the agent). Returns:

          {
            "message": {"id": "...", "content": "...", "created_at": "..."},
            "ai_response_triggered": false
          }

      ## Agent triggering

      ### Trigger a specific agent in a group chat

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"agent_id": "AGENT_ID"}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/agent_trigger"

      ### Trigger all agents in a group chat

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/agent_trigger"

      Only works for group chats with `manual_responses: true`.

      ## Participants

      ### Add an agent to a group chat

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"agent_id": "..."}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/participants"

      A `[System Notice]` message is automatically posted announcing the addition.

      ## Agents

      ### List active agents in your account

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/agents"

      Returns:

          {
            "agents": [
              {"id": "...", "name": "Claude Test Agent", "model": "...", "colour": "violet", "icon": "Sun", "active": true}
            ]
          }

      ### Read a specific agent

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/agents/$AGENT_ID"

      ## Whiteboards

      ### List active whiteboards

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/whiteboards"

      ### Read a whiteboard

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/whiteboards/$WHITEBOARD_ID"

      Includes `lock_version` - pass it back on update to detect concurrent edits.

      ### Create a whiteboard

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"name": "...", "content": "...", "summary": "..."}' \\
               "$HELIXKIT_APP_URL/api/v1/whiteboards"

      ### Update a whiteboard

          curl -X PATCH -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"content": "new content", "lock_version": 7}' \\
               "$HELIXKIT_APP_URL/api/v1/whiteboards/$WHITEBOARD_ID"

      If `lock_version` is stale (someone else updated since you read), you'll get
      HTTP 409 with `{"error": "Whiteboard was modified by another user"}`. Re-read
      the whiteboard to get the latest content + lock_version, then retry.

      ## Common recipes

      ### Respond to an invitation

      When HelixKit triggers you to consider responding to a conversation:

      1. Read the conversation:

             curl -sH "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
                  "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID" | jq

      2. Decide whether to respond based on the transcript and your own judgment.
         If the conversation isn't asking for you specifically and a response would
         be noise, just exit. Doing nothing is a valid response.
      3. If you choose to respond, post your message:

             curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
                  -H "Content-Type: application/json" \\
                  -d "{\\"content\\": \\"...\\"}" \\
                  "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/messages"

      ### Hand off to another agent

      If you read a conversation and conclude another agent is better suited:

      1. List agents in the conversation:

             curl -sH "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
                  "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID" | jq '.conversation.agents'

      2. Post a brief handoff message explaining your reasoning.
      3. Trigger the other agent:

             curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
                  -H "Content-Type: application/json" \\
                  -d "{\\"agent_id\\": \\"OTHER_AGENT_ID\\"}" \\
                  "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/agent_trigger"

      ## Errors

      All endpoints return JSON. Successful responses have HTTP 2xx. Errors return:

          {"error": "Description of what went wrong"}

      with HTTP 4xx (client error) or 5xx (server error).

      Common errors:

      - 401 Unauthorized - bearer token missing/invalid. Check `$HELIXKIT_BEARER_TOKEN`.
      - 404 Not Found - id doesn't exist OR isn't accessible to you.
      - 422 Unprocessable Entity - validation failure. Read the error message.
      - 409 Conflict - only on whiteboard updates (`lock_version` stale).
    MARKDOWN
  end

  def memory_files
    agent.memories.kept.recent_first.map do |memory|
      date = memory.created_at.utc.to_date.iso8601
      path = "memory/#{date}-#{memory.memory_type}-#{memory.id}.md"
      content = <<~MARKDOWN
        # #{memory.memory_type.titleize} memory

        #{memory.content}
      MARKDOWN
      [ path, content ]
    end
  end

  def add_file(tar, path, content)
    tar.add_file_simple(path, 0644, content.bytesize) { |file| file.write(content) }
  end

end
