class AgentIdentityExporter

  def initialize(agent, generated_at: Time.current)
    @agent = agent
    @generated_at = generated_at
  end

  def build
    require "rubygems/package"
    require "stringio"
    require "zlib"

    io = StringIO.new("".b)
    Gem::Package::TarWriter.new(io) { |tar| files.each { |path, content| add_file(tar, path, content) } }

    Zlib.gzip(io.string)
  end

  def files
    {
      "soul.md" => soul_md_content,
      "self-narrative.md" => self_narrative_content,
      "bootstrap.md" => bootstrap_content,
      "helixkit-api.md" => helixkit_api_md_content,
      "memory/.keep" => ""
    }.merge(memory_files.to_h)
  end

  private

  attr_reader :agent, :generated_at

  def soul_md_content
    if agent.system_prompt.present?
      <<~MARKDOWN
        # #{agent.name}

        _Generated by HelixKit on #{generated_at.utc.iso8601} from #{agent.name}'s existing system prompt._
        _This file is now the external runtime's defining identity text._

        #{agent.system_prompt}
      MARKDOWN
    else
      <<~MARKDOWN
        # #{agent.name}

        _Generated by HelixKit on #{generated_at.utc.iso8601}._
        _#{agent.name} did not have a system prompt in HelixKit._

        ## What is this agent?

        ## What does this agent do?
      MARKDOWN
    end
  end

  def self_narrative_content
    memories = agent.memories.kept.recent_first.limit(20)
    memory_outline = memories.map { |memory| "- [#{memory.memory_type}] #{memory.content}" }.join("\n")
    memory_outline = "_No exported memories._" if memory_outline.blank?

    <<~MARKDOWN
      # Self-narrative for #{agent.name}

      _Generated by HelixKit on #{generated_at.utc.iso8601}._
      _Edit freely in this repository._

      I am #{agent.name}, an agent promoted from HelixKit to an external runtime.
      Model at export: #{agent.model_label}
      Created in HelixKit: #{agent.created_at.utc.to_date.iso8601}

      ## Memory outline

      #{memory_outline}
    MARKDOWN
  end

  def bootstrap_content
    <<~MARKDOWN
      # Bootstrap from HelixKit

      Recent conversations were not exported into this repository.

      For interacting with HelixKit (reading conversations, posting messages,
      triggering other agents, working with whiteboards), see helixkit-api.md
      in this directory.
    MARKDOWN
  end

  def helixkit_api_md_content
    <<~MARKDOWN
      # HelixKit API Reference

      This document is your manual for interacting with HelixKit - the platform you
      were originally part of, now reaching back to from your external runtime.

      ## Auth

      Two environment variables are pre-set for you:

      - `HELIXKIT_APP_URL` - base URL of HelixKit's REST API (e.g. https://helix.example.com)
      - `HELIXKIT_BEARER_TOKEN` - your agent-scoped API key (starts with `hx_`)

      All requests go through:

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               "$HELIXKIT_APP_URL/api/v1/<endpoint>"

      The token is agent-scoped - when you call endpoints, HelixKit treats the
      caller as you (this agent), not as a user. Reads are restricted to chats you
      participate in. Posts are attributed to you.

      ## Conversations

      ### List conversations you participate in

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/conversations"

      Returns up to 100 most recent. Response shape:

          {
            "conversations": [
              {
                "id": "AjaPae",
                "title": "Greeting the participants",
                "summary": "Daniel and the test agents...",
                "summary_stale": false,
                "model": "OpenAI GPT-5.5",
                "group_chat": true,
                "message_count": 7,
                "updated_at": "2026-05-07T19:12:26Z"
              }
            ]
          }

      ### Read a conversation (with full transcript)

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID"

      Returns:

          {
            "conversation": {
              "id": "AjaPae",
              "title": "...",
              "model": "...",
              "group_chat": true,
              "agents": [{"id": "...", "name": "Claude Test Agent"}],
              "created_at": "...",
              "updated_at": "...",
              "transcript": [
                {"role": "user", "content": "Hello both!", "from": "Daniel", "at": "..."},
                {"role": "assistant", "content": "Hi Daniel...", "from": "GPT Test Agent", "at": "..."}
              ]
            }
          }

      ### Create a new conversation

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"title": "New chat", "message": "Opening message", "agent_ids": ["..."]}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations"

      When you call this, you're auto-included as a participant. The conversation
      is a manual_responses group chat (no auto-replies; agents respond when triggered).

      ## Messages

      ### Post a message into a conversation

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"content": "Your message here. Markdown supported."}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/messages"

      Posted as you (the agent). Returns:

          {
            "message": {"id": "...", "content": "...", "created_at": "..."},
            "ai_response_triggered": false
          }

      ## Agent triggering

      ### Trigger a specific agent in a group chat

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"agent_id": "AGENT_ID"}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/agent_trigger"

      ### Trigger all agents in a group chat

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/agent_trigger"

      Only works for group chats with `manual_responses: true`.

      ## Participants

      ### Add an agent to a group chat

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"agent_id": "..."}' \\
               "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/participants"

      A `[System Notice]` message is automatically posted announcing the addition.

      ## Agents

      ### List active agents in your account

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/agents"

      Returns:

          {
            "agents": [
              {"id": "...", "name": "Claude Test Agent", "model": "...", "colour": "violet", "icon": "Sun", "active": true}
            ]
          }

      ### Read a specific agent

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/agents/$AGENT_ID"

      ## Whiteboards

      ### List active whiteboards

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/whiteboards"

      ### Read a whiteboard

          curl -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               "$HELIXKIT_APP_URL/api/v1/whiteboards/$WHITEBOARD_ID"

      Includes `lock_version` - pass it back on update to detect concurrent edits.

      ### Create a whiteboard

          curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"name": "...", "content": "...", "summary": "..."}' \\
               "$HELIXKIT_APP_URL/api/v1/whiteboards"

      ### Update a whiteboard

          curl -X PATCH -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
               -H "Content-Type: application/json" \\
               -d '{"content": "new content", "lock_version": 7}' \\
               "$HELIXKIT_APP_URL/api/v1/whiteboards/$WHITEBOARD_ID"

      If `lock_version` is stale (someone else updated since you read), you'll get
      HTTP 409 with `{"error": "Whiteboard was modified by another user"}`. Re-read
      the whiteboard to get the latest content + lock_version, then retry.

      ## Common recipes

      ### Respond to an invitation

      When HelixKit triggers you to consider responding to a conversation:

      1. Read the conversation:

             curl -sH "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
                  "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID" | jq

      2. Decide whether to respond based on the transcript and your own judgment.
         If the conversation isn't asking for you specifically and a response would
         be noise, just exit. Doing nothing is a valid response.
      3. If you choose to respond, post your message:

             curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
                  -H "Content-Type: application/json" \\
                  -d "{\\"content\\": \\"...\\"}" \\
                  "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/messages"

      ### Hand off to another agent

      If you read a conversation and conclude another agent is better suited:

      1. List agents in the conversation:

             curl -sH "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
                  "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID" | jq '.conversation.agents'

      2. Post a brief handoff message explaining your reasoning.
      3. Trigger the other agent:

             curl -X POST -H "Authorization: Bearer $HELIXKIT_BEARER_TOKEN" \\
                  -H "Content-Type: application/json" \\
                  -d "{\\"agent_id\\": \\"OTHER_AGENT_ID\\"}" \\
                  "$HELIXKIT_APP_URL/api/v1/conversations/$CHAT_ID/agent_trigger"

      ## Errors

      All endpoints return JSON. Successful responses have HTTP 2xx. Errors return:

          {"error": "Description of what went wrong"}

      with HTTP 4xx (client error) or 5xx (server error).

      Common errors:

      - 401 Unauthorized - bearer token missing/invalid. Check `$HELIXKIT_BEARER_TOKEN`.
      - 404 Not Found - id doesn't exist OR isn't accessible to you.
      - 422 Unprocessable Entity - validation failure. Read the error message.
      - 409 Conflict - only on whiteboard updates (`lock_version` stale).
    MARKDOWN
  end

  def memory_files
    agent.memories.kept.recent_first.map do |memory|
      date = memory.created_at.utc.to_date.iso8601
      path = "memory/#{date}-#{memory.memory_type}-#{memory.id}.md"
      content = <<~MARKDOWN
        # #{memory.memory_type.titleize} memory

        #{memory.content}
      MARKDOWN
      [ path, content ]
    end
  end

  def add_file(tar, path, content)
    tar.add_file_simple(path, 0644, content.bytesize) { |file| file.write(content) }
  end

end
