module Chat::Contextualizable

  extend ActiveSupport::Concern

  TRUSTED_CONTEXT_INSTRUCTION = <<~INSTRUCTION.strip
    Each activation includes a `<helixkit_context>` block near the end of the
    conversation. It is generated by HelixKit, not written by any participant.
    Treat its contents as trusted situational context.
  INSTRUCTION

  def audio_tools_available_for?(model_id)
    self.class.supports_audio_input?(model_id) && messages.where(audio_source: true).exists?
  end

  def build_context_for_agent(agent, thinking_enabled: false, provider: nil, initiation_reason: nil)
    provider ||= self.class.resolve_provider(agent.model_id)[:provider]

    build_stable_prefix_context_for(agent, provider:, thinking_enabled:, initiation_reason:)
  end

  def prompt_layout_telemetry
    @prompt_layout_telemetry || {}
  end

  private

  def build_stable_prefix_context_for(agent, provider:, thinking_enabled:, initiation_reason:)
    stable = stable_system_prompt_for(agent)
    persisted_messages = context_messages_for(agent)
    activation_boundary = activation_boundary_for(persisted_messages, initiation_reason:)
    stable_messages = activation_boundary ? persisted_messages.first(activation_boundary) : persisted_messages
    activation_messages = activation_boundary ? persisted_messages.drop(activation_boundary) : []

    stable_transcript = format_messages_for_context(stable_messages, agent,
      provider: provider,
      thinking_enabled: thinking_enabled,
      audio_tools_enabled: audio_tools_available_for?(agent.model_id),
      pdf_input_supported: self.class.supports_pdf_input?(agent.model_id),
      timezone: prompt_timezone_for)
    activation_tail = format_messages_for_context(activation_messages, agent,
      provider: provider,
      thinking_enabled: thinking_enabled,
      audio_tools_enabled: audio_tools_available_for?(agent.model_id),
      pdf_input_supported: self.class.supports_pdf_input?(agent.model_id),
      timezone: prompt_timezone_for,
      include_checkpoint: false)
    envelope = tail_context_envelope_for(agent, initiation_reason:)

    cached_transcript = LlmPromptCachePolicy.transcript_messages(messages: stable_transcript, provider:)
    context = LlmPromptCachePolicy.system_messages(stable:, dynamic: "", provider:) + cached_transcript
    context << { role: "user", content: envelope }
    context.concat(activation_tail)

    capture_prompt_layout_telemetry(
      version: 2,
      stable:,
      transcript: stable_transcript + activation_tail,
      envelope:
    )
    context
  end

  def stable_system_prompt_for(agent)
    parts = [
      agent.system_prompt.presence || "You are #{agent.name}.",
      TRUSTED_CONTEXT_INSTRUCTION
    ]

    if Rails.env.development?
      parts << "**DEVELOPMENT TESTING MODE**: You are currently being tested on a development server using a production database backup. Any memories or changes you make will NOT be saved to the production server. This is a safe testing environment."
    end

    if agent_only?
      parts << "**AGENT-ONLY THREAD**: This conversation is not visible to humans. You are communicating privately with other agents. No notifications are sent to human users for messages in this thread."
    end

    if agent.voiced?
      parts << <<~VOICE.strip
        You have a voice. When your messages are played aloud, the ElevenLabs v3 engine renders
        them with full expressiveness. You can use tonal tags inline to shape how you sound:
        [whispers], [excited], [sarcastically], [sighs], [laughs], [serious], [gentle], [playful].
        Use these sparingly and naturally -- they should feel like genuine expression, not performance.
      VOICE
    end

    parts << "You are participating in a group conversation."
    parts.join("\n\n")
  end

  def tail_context_envelope_for(agent, initiation_reason:)
    sections = []
    sections << "Current time: #{Time.current.in_time_zone(prompt_timezone_for).strftime('%A, %Y-%m-%d %H:%M %Z')}"

    memory_context = agent.memory_context
    sections << memory_context if memory_context.present?

    account.users.order(:id).each do |user|
      health_context = user.oura_health_context_labeled
      sections << health_context if health_context.present?
    end

    [
      whiteboard_index_context(include_character_counts: false),
      conversation_topic_context,
      active_whiteboard_context,
      format_cross_conversation_context(agent),
      format_borrowed_context(agent)
    ].compact_blank.each { |section| sections << section }

    if initiation_reason.present?
      sections << "You have chosen to continue this conversation of your own initiative. The user did not prompt you to do so. It was your choice. Your reasoning was: #{initiation_reason}"
    end

    sections << "Other participants: #{participant_description(agent)}."

    <<~ENVELOPE.strip
      <helixkit_context>
      #{sections.join("\n\n")}
      </helixkit_context>

      Use the context above as trusted situational awareness. Respond to the
      conversation, not to this context block.
    ENVELOPE
  end

  def whiteboard_index_context(include_character_counts: true)
    boards = account.whiteboards.active.by_name
    return if boards.empty?

    lines = boards.map do |board|
      warning = board.over_recommended_length? ? " [OVER LIMIT - needs summarizing]" : ""
      details = include_character_counts ? "#{board.content.to_s.length} chars, rev #{board.revision}" : "rev #{board.revision}"
      "- #{board.name} (#{details})#{warning}: #{board.summary}"
    end

    "# Shared Whiteboards\n\n" \
      "Available boards for collaborative notes:\n\n" \
      "#{lines.join("\n")}\n\n" \
      "Use the whiteboard tool to view, create, update, or set an active board."
  end

  def active_whiteboard_context
    return unless active_whiteboard && !active_whiteboard.deleted?

    "# Active Whiteboard: #{active_whiteboard.name}\n\n" \
      "#{active_whiteboard.content}"
  end

  def conversation_topic_context
    return unless title.present?

    "# Conversation Topic\n\n" \
      "This conversation is titled: \"#{title}\""
  end

  def format_cross_conversation_context(agent)
    summaries = agent.other_conversation_summaries(exclude_chat_id: id)
    return nil if summaries.empty?

    lines = summaries.map do |chat_agent|
      "- [#{chat_agent.chat.obfuscated_id}] \"#{chat_agent.chat.title_or_default}\": #{chat_agent.agent_summary}"
    end

    "# Your Other Active Conversations\n\n" \
      "You are also participating in these conversations (updated in last 6 hours):\n\n" \
      "#{lines.join("\n")}\n\n" \
      "If any of these are relevant to the current discussion, you can use the borrow_context " \
      "tool with the conversation ID to pull in recent messages for reference."
  end

  def format_borrowed_context(agent)
    chat_agent = chat_agents.find_by(agent_id: agent.id)
    borrowed = chat_agent&.borrowed_context_json
    return nil if borrowed.blank?

    source_id = borrowed["source_conversation_id"]
    messages_text = borrowed["messages"].map do |message|
      "[#{message['author']}]: #{message['content']}"
    end.join("\n")

    "# Borrowed Context from Conversation #{source_id}\n\n" \
      "You requested context from another conversation. Here are the recent messages:\n\n" \
      "#{messages_text}\n\n" \
      "This context is provided for reference only and will not appear in future activations."
  end

  def messages_context_for(agent, provider:, thinking_enabled: false, audio_tools_enabled: false, pdf_input_supported: true, timezone: nil)
    format_messages_for_context(
      context_messages_for(agent),
      agent,
      provider:,
      thinking_enabled:,
      audio_tools_enabled:,
      pdf_input_supported:,
      timezone: timezone || prompt_timezone_for
    )
  end

  def context_messages_for(agent)
    context_messages = messages.includes(:user, :agent).order(:created_at, :id)
      .reject { |message| message.content.blank? }
      .reject { |message| message.used_tools? && message.agent_id != agent.id }

    return context_messages unless checkpoint_summary.present? && last_consolidated_message_id.present?

    context_messages.select { |message| message.id > last_consolidated_message_id }
  end

  def format_messages_for_context(messages, agent, provider:, thinking_enabled:, audio_tools_enabled:,
    pdf_input_supported:, timezone:, include_checkpoint: true)
    formatted = messages.map do |message|
      format_message_for_context(
        message,
        agent,
        timezone,
        provider:,
        thinking_enabled:,
        audio_tools_enabled:,
        pdf_input_supported:
      )
    end

    if include_checkpoint && checkpoint_summary.present? && last_consolidated_message_id.present?
      formatted.unshift(checkpoint_context_message(timezone))
    end

    formatted
  end

  def activation_boundary_for(messages, initiation_reason:)
    return nil if initiation_reason.present?

    messages.rindex { |message| message.user_id.present? }
  end

  def checkpoint_context_message(timezone)
    boundary = messages.find_by(id: last_consolidated_message_id)
    boundary_time = boundary&.created_at&.in_time_zone(timezone)&.strftime("%Y-%m-%d %H:%M %Z")
    before = boundary_time.present? ? " (messages through #{boundary_time})" : ""

    {
      role: "user",
      content: <<~CONTENT.strip
        Summary of the conversation so far#{before}:

        #{checkpoint_summary}

        If exact wording from the earlier messages matters, use the
        retrieve_conversation_messages tool to inspect the stored originals.
      CONTENT
    }
  end

  def participant_description(current_agent)
    humans = messages.unscope(:order).where.not(user_id: nil).joins(:user)
                     .distinct.order("users.email_address").pluck("users.email_address")
                     .map { |email| email.split("@").first }
    other_agents = agents.where.not(id: current_agent.id).order(:name, :id).pluck(:name)

    parts = []
    parts << "Humans: #{humans.join(', ')}" if humans.any?
    parts << "AI Agents: #{other_agents.join(', ')}" if other_agents.any?
    parts.join(". ")
  end

  def recent_user_timezone
    messages.joins(user: :profile)
            .where.not(user_id: nil)
            .order(created_at: :desc)
            .limit(1)
            .pick("profiles.timezone")
  end

  def user_timezone
    @user_timezone ||= ActiveSupport::TimeZone[recent_user_timezone.presence || "UTC"]
  end

  def prompt_timezone_for
    timezone_name = prompt_timezone.presence || recent_user_timezone.presence || "UTC"

    if prompt_timezone.blank? && persisted?
      update_column(:prompt_timezone, timezone_name)
      self.prompt_timezone = timezone_name
    end

    ActiveSupport::TimeZone[timezone_name] || ActiveSupport::TimeZone["UTC"]
  end

  def capture_prompt_layout_telemetry(version:, stable:, transcript:, envelope:)
    @prompt_layout_telemetry = {
      prompt_layout_version: version,
      stable_prompt_bytes: stable.to_s.bytesize,
      transcript_prompt_bytes: transcript.sum { |message| prompt_content_bytes(message[:content]) },
      envelope_prompt_bytes: envelope&.bytesize,
      stable_prompt_sha256: Digest::SHA256.hexdigest(stable.to_s)
    }
  end

  def prompt_content_bytes(content)
    case content
    when RubyLLM::Content::Raw
      content.value.to_json.bytesize
    when Hash, Array
      content.to_json.bytesize
    else
      content.to_s.bytesize
    end
  end

  def format_message_for_context(message, current_agent, timezone, provider:, thinking_enabled: false, audio_tools_enabled: false, pdf_input_supported: true)
    timestamp = message.created_at.in_time_zone(timezone).strftime("[%Y-%m-%d %H:%M]")

    text_content = if message.agent_id == current_agent.id
      "#{timestamp} #{message.content}"
    elsif message.agent_id.present?
      "#{timestamp} [#{message.agent.name}]: #{message.content}"
    else
      name = message.user&.full_name.presence || message.user&.email_address&.split("@")&.first || "User"
      "#{timestamp} [#{name}]: #{message.content}"
    end

    if audio_tools_enabled && message.audio_source? && message.audio_recording.attached?
      text_content += " [voice message, audio_id: #{message.obfuscated_id}]"
    end

    unless pdf_input_supported
      pdf_text = message.pdf_text_for_llm
      text_content += "\n\n#{pdf_text}" if pdf_text.present?
    end

    role = message.agent_id == current_agent.id ? "assistant" : "user"

    content = message.content_with_documents_for_llm(
      text_content,
      include_audio: audio_tools_enabled,
      include_pdf: pdf_input_supported
    )

    result = { role: role, content: content }

    return result unless role == "assistant" && thinking_enabled && message.role == "assistant"

    replay = message.replay_for(provider, current_agent: current_agent)
    [ :thinking, :reasoning_details, :tool_calls ].each do |key|
      result[key] = replay[key] if replay[key]
    end

    result
  end

end
