# config/deploy.yml

service: helix-kit
image: dtenner/helix-kit

registry:
  username: dtenner
  password:
  - KAMAL_REGISTRY_PASSWORD

ssh:
  user: swombat
  port: 12222 # This is the SSH port for your server

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true # Let Rails serve static files (since no external proxy in production)
    RAILS_LOG_TO_STDOUT: true # Log to STDOUT for Docker logging
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY # Rails master key (provide in .kamal/secrets)
    - DATABASE_URL # Database connection string (provided per env in secrets)

servers:
  web:
    hosts:
      - 95.217.118.47
  jobs:
    hosts:
      - 95.217.118.47
    cmd: ["./bin/rails", "solid_queue:start"]

proxy:
  ssl: true
  host: helix-kit.granttree.co.uk
  app_port: 3000

builder:
  arch: amd64
  remote: ssh://swombat@95.217.118.47:12222
  args:
    RAILS_ENV: production

accessories:
  postgres:
    image: postgres:16.2 # Use the correct version for your app
    host: 95.217.118.47
    env:
      clear:
        POSTGRES_USER: helix_kit
        POSTGRES_DB: helix_kit_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data # Persist db data on host (named volume "data")
